- name: Setup Env
  hosts:
    - aws
  vars:
    maven_version: 3.3.9
    maven_file_name: "apache-maven-{{ maven_version }}"
    maven_dest_dir: "/usr/local"
    tmp_dir: "{{ ansible_ssh_user }}/tmp"
  tasks:

    - name: create tmp dir
      file: path={{ tmp_dir }} state=directory mode=0755

    - name: create mvn dest dir
      file: path={{ maven_dest_dir }} state=directory mode=0755
      become: yes

    - name: create mvn extract dir
      file: path={{ maven_dest_dir }}/{{ maven_file_name }} state=directory mode=0755
      become: yes

    - name: get maven
      # ansible > 2
      # get_url: url=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=~/maven/ checksum=md5:516923b3955b6035ba6b0a5b031fbd8b
      get_url: url=http://apache.mivzakim.net/maven/maven-3/{{ maven_version }}/binaries/{{ maven_file_name }}-bin.tar.gz dest={{ tmp_dir }}

    - name: extract maven
      unarchive: copy=no src={{ tmp_dir }}/{{ maven_file_name }}-bin.tar.gz dest={{ maven_dest_dir }} mode=0755
      become: yes

    - name: symlink maven
      file: src={{ maven_dest_dir }}/{{ maven_file_name }} dest={{ maven_dest_dir }}/maven state=link
      become: yes

  tags:
    - setup